logging:
  config: classpath:logs/logback-local.xml

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: khjzzm
    password: ENC(Dh20sGMupJaGJojuf5ZDoIzL3IeDdT3tLLZZfEGuFnA=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/lunch
    username: sa
    password:
    driver-class-name: org.h2.Driver
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true # SQL 출력
        use_sql_comments: true # JPQL 출력
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Hibernate sql
    defer-datasource-initialization: true
    open-in-view: true

  redis:
    master:
      host:
      port:
    slaves:
      - host:
        port:
    password:
    database:

  sql:
    init:
      mode: never

file:
  upload:
    root-path: ./file
    ratio-wh: 1280

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: false

dalla:
#  baseUrl: https://devapi.dallalive.com
#  authToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxQDEuY29tIiwianRpIjoiOTViOTQ4OWYtYThkYS00OTY5LTlhYmUtZjY2OGJiMmM1MjFmIiwiaXNzIjoieWVvYm95YSIsImlhdCI6MTY5NTcwMzY0MywiZXhwIjoxNjk1NzQ2ODQzLCJhdXRoIjoiUk9MRV9VU0VSIn0.xGd7FmSkNXw8GSt8fExhkFWFHiPpjYCdDatseO_zZ08
  baseUrl: https://api.dallalive.com
  authToken: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTU4NzA4NzI0MzEwNkB0cnVlIiwiaWF0IjoxNzA0MTU0OTA5LCJleHAiOjE3MDY3NDY5MDl9.BfkvPiCSlMZON2qCYTVTGz4HDJ2-pQc2jyBpGDDjmFA
  socketUrl: https://devsv1.dallalive.com:8000/api/chatroom/sendmessage/
