logging:
  config: classpath:logs/logback-dev.xml

spring:
  datasource:
    hikari:
      master:
        jdbcUrl: ENC(rXD3LhzZaoLUP8MZsvnYxuou7znO1P5eO4JZNqZwH/3eHj8/7M0WKxmsKcf6RoqJf21bMs2HZmI=)
        username: ENC(M/tnB43FoA03zzaPXaZSuA==)
        password: ENC(CshQkcD3r93r6dVS4p5UtXJV7c8k+qpu)
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        poolName: kimzzang-db-master
      slave:
        jdbcUrl: ENC(rXD3LhzZaoLUP8MZsvnYxuou7znO1P5eO4JZNqZwH/3eHj8/7M0WKxmsKcf6RoqJf21bMs2HZmI=)
        username: ENC(M/tnB43FoA03zzaPXaZSuA==)
        password: ENC(CshQkcD3r93r6dVS4p5UtXJV7c8k+qpu)
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        poolName: kimzzang-db-master

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
        show_sql: 'true'
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: true

  redis:
    master:
      host: ENC(+ahrQw0vlB6Kj/bGjnin2xbvGRPwjFJN)
      port: 6380
    slaves:
      - host: ENC(+ahrQw0vlB6Kj/bGjnin2xbvGRPwjFJN)
        port: 6381
    password: ENC(wXDtXa+LzvTJI8S77PmGxJz35uoG8N2B)
    database: 12
