logging:
  config: classpath:logs/logback-local.xml

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lunch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  redis:
    master:
      host: ENC(1si6oObr2Zun8ln/OqBZ9szKhr4xO0YO)
      port: 6379
    slaves:
      - host: ENC(1si6oObr2Zun8ln/OqBZ9szKhr4xO0YO)
        port: 6379
    password: ENC(k3+uuE0Hqnuha51Lh9UWXyZWi/mXk7Q1)
    database: 0
