spring:
  profiles:
    active: "local"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(msnXO/qwDDzrDVxBzJSA39GjTJTgNJlo24Ii6fmYxi4=)
    password: ENC(NOQd4VVQYDKVJm1XJxmGlaETq76lg+c8CUS9YmndAxs=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: CAFFEINE

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      repositories:
        enabled: false

  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

server:
#  port: 4463
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 9000
  info:
    java:
      enabled: true # Java 관련 정보도 출력될 수 있게 합니다.
    os:
      enabled: true # OS 관련 정보도 출력될 수 있게 합니다.
    git:
      mode: "full" # Git 정보를 'full' 모드로 표시하게 합니다.
  endpoint:
    prometheus:
      enabled: true # Prometheus 미터 등록 정보를 사용 가능하게 합니다.
    shutdown:
      enabled: true # Shut down end point를 사용 가능하게 합니다. 이 end point를 호출하면 서비스가 정지됩니다.
    health:
      show-details: always # Health check end point가 항상 자세한 정보를 출력하도록 합니다.
  endpoints:
    web:
      exposure:
        include: "*" # 모든 웹 기반 end point가 사용 가능하게 보이도록 설정합니다.
  health:
    db:
      enabled: true

file:
  upload:
    root-path: ./file
    ratio-wh: 1280

jwt:
  token:
    secretKey: CY9AK5nbR9Ok66F+oJvk+AA/8/cShipQoICTd8m4ZLVu6PcNHnL8WRhOVqDl3WNTFqoEw32HIzu1qYaW4GfPbDgrC+hPnpMmjPHeDckqdLs28oF4vunHQpg1dVcoD65t
