spring:
  profiles:
    active: "local"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(5IBoYtY2KEjrpcjkfNcZUQ6Alpp8d5nxkTC4nGBXeGw=)
    password: ENC(Dh20sGMupJaGJojuf5ZDoIzL3IeDdT3tLLZZfEGuFnA=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: CAFFEINE

  data:
    web:
      pageable:
        one-indexed-parameters: true

  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

server:
  port: 463
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    default-fetch-size: '100'
    default-statement-timeout: '30'
    map-underscore-to-camel-case: 'true'

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  token:
    secretKey: ENC(CY9AK5nbR9Ok66F+oJvk+AA/8/cShipQoICTd8m4ZLVu6PcNHnL8WRhOVqDl3WNTFqoEw32HIzu1qYaW4GfPbDgrC+hPnpMmjPHeDckqdLs28oF4vunHQpg1dVcoD65t)
