logging:
  config: classpath:logs/logback-local.xml

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: khjzzm
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/lunch
    username: sa
    password:
    driver-class-name: org.h2.Driver
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true # SQL 출력
        use_sql_comments: true # JPQL 출력
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true # Hibernate sql
    defer-datasource-initialization: true
  #    open-in-view: false

  redis:
    master:
      host:
      port:
    slaves:
      - host:
        port:
    password:
    database:

  sql:
    init:
      mode: never

file:
  upload:
    root-path: ./file
    ratio-wh: 1280

decorator:
  datasource:
    p6spy:
      enable-logging: true

dalla:
  baseUrl: https://api.dallalive.com
  authToken:

