spring:
  profiles:
    active: "local"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(msnXO/qwDDzrDVxBzJSA39GjTJTgNJlo24Ii6fmYxi4=)
    password: ENC(NOQd4VVQYDKVJm1XJxmGlaETq76lg+c8CUS9YmndAxs=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: CAFFEINE

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      repositories:
        enabled: false

  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

server:
  port: 4463
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 9292
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: "full"
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

file:
  upload:
    root-path: ./file
    ratio-wh: 1280

jwt:
  token:
    secretKey: CY9AK5nbR9Ok66F+oJvk+AA/8/cShipQoICTd8m4ZLVu6PcNHnL8WRhOVqDl3WNTFqoEw32HIzu1qYaW4GfPbDgrC+hPnpMmjPHeDckqdLs28oF4vunHQpg1dVcoD65t
