logging:
  config: classpath:logs/logback-local.xml

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: khjzzm
    password: snpmkpsycogrolbm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/lunch
    username: sa
    password:
    driver-class-name: org.h2.Driver
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
#        show_sql: true # SQL 출력
#        use_sql_comments: true # JPQL 출력
#        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto : update
    show-sql: true # Hibernate sql
    defer-datasource-initialization: true
#    open-in-view: false

  redis:
    master:
      host: 125.141.223.94
      port: 6380
    slaves:
      - host: 125.141.223.94
        port: 6381
    password: inforex((.(
    database: 12

  sql:
    init:
      mode: never

file:
  upload:
    root-path : ./file
    ratio-wh: 1280

decorator:
  datasource:
    p6spy:
      enable-logging: true

dalla:
  baseUrl: https://api.dallalive.com
#  baseUrl: https://devm-khj2.dallalive.com:463
  authToken: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTU4NzA4NzI0MzEwNkB0cnVlIiwiaWF0IjoxNjgwODU2NjczLCJleHAiOjE2ODM0NDg2NzN9.lxg6ztuYw5NfwyVORZjBC2GoT85hSSlCzZyhxTDHlJ0

