logging:
  config: classpath:logs/logback-prod.xml

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true # SQL 출력
        use_sql_comments: true # JPQL 출력
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true # Hibernate sql
    defer-datasource-initialization: true
    open-in-view: true

  redis:
    master:
      host: ENC(XL/QSgTlRwOUfVRZSOZbSaDCaI2VNJxXoE3nWPrOYsovA/t3rf00N5tGw6YU8W0wJxw387AsK36bKVPfA/2stNtxdb2CdneC)
      port: 10143
    slaves:
      - host: ENC(XL/QSgTlRwOUfVRZSOZbSaDCaI2VNJxXoE3nWPrOYsovA/t3rf00N5tGw6YU8W0wJxw387AsK36bKVPfA/2stNtxdb2CdneC)
        port: 10143
    password: ENC(ZMI0vFbTTHnB6wP3MXLNZzvTbb5RnlY1nj8a3uH7He5YoS8vAd1UA/JcssiLrS7x)
    database: 0
