logging:
  config: classpath:log/logback-dev.xml

spring:
  datasource:
    hikari:
      master:
        jdbcUrl: ENC(BjbrdO2e9XfD5LHjkFwk2wP0ros/23gQbwTKYkU1/3TfUmVJA/C+MwuwRja96VxbXIGLYg1NVVFa30Qp3zl5Ww==)
        username: ENC(Z+0grMiwTWpfJnhBX4nd9w==)
        password: ENC(RvZJmjpJdTdsKIdCevNZNyTWjLw3XXPn)
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        poolName: kimzzang-db-master
      slave:
        jdbcUrl: ENC(BjbrdO2e9XfD5LHjkFwk2wP0ros/23gQbwTKYkU1/3TfUmVJA/C+MwuwRja96VxbXIGLYg1NVVFa30Qp3zl5Ww==)
        username: ENC(Z+0grMiwTWpfJnhBX4nd9w==)
        password: ENC(RvZJmjpJdTdsKIdCevNZNyTWjLw3XXPn)
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        poolName: kimzzang-db-master
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
        show_sql: 'true'
        generate_statistics: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

  redis:
    master:
      host: ENC(LoE2TV1irncIGXTtYFDTMqvnbgLa7DBi)
      port: 6380
    slaves:
      - host: ENC(LoE2TV1irncIGXTtYFDTMqvnbgLa7DBi)
        port: 6381
    password: ENC(FtsNreuQ5/JR69WxVWZxxWQi0sO0JGRY)
    database: 12


