name: yeoboya-lunch-api CI # 워크플로우의 이름을 지정합니다.

on:
  push:
    branches: [ main ] # main 브랜치에 푸시가 발생할 경우 워크플로우를 시작합니다.
  pull_request:
    branches: [ main ] # main 브랜치에 PR(pull request)이 발생할 경우 워크플로우를 시작합니다.

jobs:
  build:
    runs-on: ubuntu-latest # 작업이 실행될 운영체제입니다. 가장 최신의 ubuntu를 사용합니다.

    steps:
      - uses: actions/checkout@v2 # 저장소를 체크아웃합니다. 이 단계에서 코드가 Runner에 복사됩니다.

      - name: Set up JDK 11 # JDK 11을 설치합니다.
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew # gradlew에 실행 권한을 부여합니다.
        run: chmod +x gradlew

      - name: Cache Gradle packages # Gradle 패키지를 캐시합니다. 이를 통해 다시 실행할 때 빌드 속도를 줄일 수 있습니다.
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle # Gradle로 빌드를 실행합니다.
        run: ./gradlew clean build -x test -Dspring.profiles.active=test # 여기서 prod 프로파일을 사용하여 빌드를 실행합니다.

      - name: Configure AWS credentials # AWS 자격 증명을 설정합니다.
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Sync output files to S3
        run: aws s3 cp ./$GITHUB_SHA.zip s3://yeoboya-lunch-s3/yeoboya-lunch-api.zip

      - name: Deploy to AWS EC2 using AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name yeoboya-lunch \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name yeoboya-lunch-code-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=yeoboya-lunch-s3,bundleType=zip,key=yeoboya-lunch-api.zip \
          --region ap-northeast-2 \
